urls.py
from django.conf.urls import url
from . import views

app_name = 'groupTracker'
urlpatterns = [
	#ex: /groupTracker
	url(r'^$', views.index, name='index'),	
	url(r'^(?P<group_id>[0-9]+)/$', views.details, name='details'),
	#url(r'^(?P<pk>\d+)/submit/$', views.submit, name='submit'),
	url(r'^submit/(?P<pk>\d+)/$', views.submit, name='submit'),
	url(r'^showAll/$', views.showAll, name='showAll'),
	url(r'^delete/$', views.delete, name='delete'),
	#url(r'^(?P<group_id>[0-9]+)/showAll/$', views.showAll, name='showAll'),
]

models.py
from django.db import models

class GroupInfo(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	group_name = models.CharField(max_length=100)
	class_name = models.CharField(max_length=100)

	def __str__(self):
		return (self.first_name + " " + self.last_name + " | " + self.group_name + " | " + self.class_name)

forms.py
from django import forms
from .models import GroupInfo

class GroupInfoForm(forms.ModelForm):

	class Meta:
		model = GroupInfo
		fields = ('first_name', 'last_name', 'group_name','class_name',)

class GroupInfoDeleteForm(forms.ModelForm):

	class Meta:
		model = GroupInfo
		fields = ('last_name','group_name',)

class GroupInfoFindForm(forms.ModelForm):

	class Meta:
		model = GroupInfo
		fields = ('class_name',)

views.py
from django.shortcuts import render, redirect, get_object_or_404 
from django.http import HttpResponse

import logging
logger = logging.getLogger(__name__)

from .forms import GroupInfoForm, GroupInfoDeleteForm, GroupInfoFindForm
from .models import GroupInfo

def index(request):
	#group = GroupInfo.objects.order_by('id')[:5]
	#context = {'group': group}
	#return render(request, 'groupTracker/index.html', context)
	if request.method == "POST":
		if 'submit' in request.POST:
			form = GroupInfoForm(request.POST)
			if form.is_valid():
				post = form.save()
				return redirect('groupTracker:submit',pk=post.pk)
		elif 'delete' in request.POST:
			searchStr = GroupInfoDeleteForm(request.POST)
			if searchStr.is_valid():
				#logger.error(searchStr)
				l_name = searchStr.cleaned_data['last_name']
				g_name = searchStr.cleaned_data['group_name']
				GroupInfo.objects.filter(last_name=l_name).filter(group_name=g_name).delete()
				return redirect('groupTracker:delete')
		elif 'find' in request.POST:
			searchStr = GroupInfoFindForm(request.POST)
			if searchStr.is_valid():
				c_name = searchStr.cleaned_data['class_name']
				records = GroupInfo.objects.filter(class_name=c_name)
				return redirect('groupTracker:details', records)
	else:
		form = GroupInfoForm()
		deleteform = GroupInfoDeleteForm()
		findform = GroupInfoFindForm()
	return render(request, 'groupTracker/index.html', {'form':form, 'deleteform':deleteform, 'findform':findform,})


def details(request,records):
	#group = get_object_or_404(GroupInfo,id=pk)
	return render(request, 'groupTracker/detail.html', {'group': records})

def showAll(request):
	#groups = get_object_or_404(GroupInfo, pk=1)
	groups = GroupInfo.objects.order_by('id')
	context = {'groups':groups}
	return render(request, 'groupTracker/showAll.html', context)

def submit(request,pk):
#	form = GroupInfoForm()
	post = get_object_or_404(GroupInfo, pk = pk)
	return render(request, 'groupTracker/details.html', {'post': post})	

def delete(request):
	return render(request, 'groupTracker/delete.html')

templates/groupTracker/delete.html
<h4>Successfully Deleted.</h4>

<form action={% url 'groupTracker:index' %}>
	<input type="submit" value="Back" />
</form>

templates/groupTracker/detail.html
<!DOCTYPE{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'groupTracker/styles.css' %}" />
{% if group %}
<div class="post">
<h4>Group:</h4>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Group Name</th>
    <th>Class Name</th>
  </tr>

    {% for item in group %}
  <tr>
    <td>{{ item.first_name }}</td>
    <td>{{ item.last_name }}</td>
    <td>{{ item.group_name }}</td>
    <td>{{ item.class_name }}</td>
  </tr>
    {% endfor %}
</table>
<form action={% url 'groupTracker:index' %}>
	<input type="submit" value="Back" />
</form>
</div>
{% else %}
	<p>No data.</p>
{% endif %}

templates/groupTracker/details.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'groupTracker/styles.css' %}" />

<div class="post">
<h4>Successfully Added.</h4>

<table style="border: 1px solid black;">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Group Name</th>
    <th>Class Name</th>
  </tr>
  <tr>
    <td>{{ post.first_name }}</td>
    <td>{{ post.last_name }}</td>
    <td>{{ post.group_name }}</td>
    <td>{{ post.class_name }}</td>
  </tr>
</table>
<form action={% url 'groupTracker:index' %}>
	<input type="submit" value="Back" />
</form>
</div>

templates/groupTracker/index.html
<h2>Group Tracker</h2>
<h4>Submit a Record:</h4>
<form method="POST" class="post-form">{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" name="submit" class="save btn btn-default">Submit</button>
</form>
<h4>Find Record:</h4>
<form method="POST">{% csrf_token %}
	{{ findform.as_p }}
	<input type="submit" name="find" value="Find Record"/>
</form>
<h4>Delete Record:</h4>
<form method="POST">{% csrf_token %}
	{{ deleteform.as_p }}
	<input type="submit" name="delete" value="Delete Record"/>
</form>
<h4>View All Records:</h4>
<form action={% url 'groupTracker:showAll' %}>
    <input type="submit" value="Show All" />
</form>

templates/groupTracker/index2.html
<form action="{% url 'groupTracker:submit' %}" method="post">
{% csrf_token %}
	First Name:<br />
	<input id="f_name" type="text" name="first_name" value="{{ first_name }}"><br />
	Last Name:<br />
	<input id="l_name" type="text" name="last_name" value="{{ last_name }}"><br />
	Group Name:<br />
	<input id="g_name" type="text" name="group_name" value="{{ group_name }}"><br />
	Class Name:<br />
	<input id="c_name" type="text" name="class_name" value="{{ class_name }}"><br />
	<input type="submit" value="Submit" />
</form>

templates/groupTracker/showAll.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'groupTracker/styles.css' %}" />

{% if groups %}
<form action={% url 'groupTracker:index' %}>
        <input type="submit" value="Back" />
</form>
    <h4>Current Groups:</h4>
    <table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Group Name</th>
    <th>Class Name</th>
  </tr>
	{% for item in groups %}
  <tr>
    <td>{{ item.first_name }}</td>
    <td>{{ item.last_name }}</td>
    <td>{{ item.group_name }}</td>
    <td>{{ item.class_name }}</td>
  </tr>
	{% endfor %}
    </table>
{% else %}
	<p>No data.</p>
{% endif %}